// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjI5slRkQ1ub1o1t5QUgP5lvzYzVxke3Q',
    appId: '1:563143214826:web:49b39d38b66be594ed3993',
    messagingSenderId: '563143214826',
    projectId: 'whatsapp-chat-9a7e7',
    authDomain: 'whatsapp-chat-9a7e7.firebaseapp.com',
    storageBucket: 'whatsapp-chat-9a7e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQCoQ4QiJDcDzZsSqVYrGHLOWIr5P-f4E',
    appId: '1:563143214826:android:09d69104ad37125bed3993',
    messagingSenderId: '563143214826',
    projectId: 'whatsapp-chat-9a7e7',
    storageBucket: 'whatsapp-chat-9a7e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_L4l6XGwFpa2w22oiVzN0bvw9oI3tPqw',
    appId: '1:563143214826:ios:834604e2a636ad48ed3993',
    messagingSenderId: '563143214826',
    projectId: 'whatsapp-chat-9a7e7',
    storageBucket: 'whatsapp-chat-9a7e7.firebasestorage.app',
    iosBundleId: 'com.example.whatsappSeries',
  );
}
